=== ryn-cx/not-yt-dlapi/src/not_yt_dlapi/playlist_item/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "nextPageToken": {"type": "string"}, "items": {"type": "array", "items": {"type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "id": {"type": "string"}, "snippet": {"type": "object", "properties": {"publishedAt": {"anyOf": [{"format": "date-time", "type": "string"}, {"type": "string", "format": "date-time"}]}, "channelId": {"type": "string"}, "title": {"type": "string"}, "description": {"type": "string"}, "thumbnails": {"type": "object", "properties": {"default": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "medium": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "high": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "standard": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "maxres": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "required": ["default", "high", "medium"]}, "channelTitle": {"type": "string"}, "playlistId": {"type": "string"}, "position": {"type": "integer"}, "resourceId": {"type": "object", "properties": {"kind": {"type": "string"}, "videoId": {"type": "string"}}, "required": ["kind", "videoId"]}, "videoOwnerChannelTitle": {"type": "string"}, "videoOwnerChannelId": {"type": "string"}}, "required": ["channelId", "channelTitle", "description", "playlistId", "position", "publishedAt", "resourceId", "thumbnails", "title", "videoOwnerChannelId", "videoOwnerChannelTitle"]}, "contentDetails": {"type": "object", "properties": {"videoId": {"type": "string"}, "videoPublishedAt": {"anyOf": [{"format": "date-time", "type": "string"}, {"type": "string", "format": "date-time"}]}}, "required": ["videoId", "videoPublishedAt"]}, "status": {"type": "object", "properties": {"privacyStatus": {"type": "string"}}, "required": ["privacyStatus"]}}, "required": ["contentDetails", "etag", "id", "kind", "snippet", "status"]}}, "pageInfo": {"type": "object", "properties": {"totalResults": {"type": "integer"}, "resultsPerPage": {"type": "integer"}}, "required": ["resultsPerPage", "totalResults"]}, "prevPageToken": {"type": "string"}}, "required": ["etag", "items", "kind", "pageInfo"]}

=== ryn-cx/not-yt-dlapi/tests/_files/Multipages/PlaylistItemsModel/UU4QobU6STFB0P71PMvOGN5A_all.json
[
  {
    "kind": "youtube#playlistItemListResponse",
    "etag": "K2q9kpGFc8MFscw9bu7ZiukS2Hc",
    "items": [
      {
        "kind": "youtube#playlistItem",
        "etag": "Lt3779X_kPPFXIYrLqwT1rLsZmE",
        "id": "VVU0UW9iVTZTVEZCMFA3MVBNdk9HTjVBLmpOUVhBQzlJVlJ3",
        "snippet": {
          "publishedAt": "2005-04-24T03:31:52Z",
          "channelId": "UC4QobU6STFB0P71PMvOGN5A",
          "title": "Me at the zoo",
          "description": "Microplastics are accumulating in human brains at an alarming rate\nhttps://www.youtube.com/watch?v=0PT5c1z3LL8\n\n\u201cNanoplastics and Human Health\u201d with Matthew J Campen, PhD, MSPH\nhttps://www.youtube.com/watch?v=RRBN_4L09Mg\n\n00:00 Intro\n00:05 The cool thing\n00:17 End",
          "thumbnails": {
            "default": {
              "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/default.jpg",
              "width": 120,
              "height": 90
            },
            "medium": {
              "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/mqdefault.jpg",
              "width": 320,
              "height": 180
            },
            "high": {
              "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg",
              "width": 480,
              "height": 360
            }
          },
          "channelTitle": "jawed",
          "playlistId": "UU4QobU6STFB0P71PMvOGN5A",
          "position": 0,
          "resourceId": {
            "kind": "youtube#video",
            "videoId": "jNQXAC9IVRw"
          },
          "videoOwnerChannelTitle": "jawed",
          "videoOwnerChannelId": "UC4QobU6STFB0P71PMvOGN5A"
        },
        "contentDetails": {
          "videoId": "jNQXAC9IVRw",
          "videoPublishedAt": "2005-04-24T03:31:52Z"
        },
        "status": {
          "privacyStatus": "public"
        }
      }
    ],
    "pageInfo": {
      "totalResults": 1,
      "resultsPerPage": 50
    }
  }
]

=== ryn-cx/not-yt-dlapi/tests/_files/PlaylistItems/TestList/TestFirstPage/PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh-2.json
{
  "kind": "youtube#playlistItemListResponse",
  "etag": "RFt0OTmmB44u1uLeHIFuiqR27as",
  "nextPageToken": "EAAaHlBUOkNBSWlFREk0T1VZMFFUUTJSRVl3UVRNd1JESQ",
  "items": [
    {
      "kind": "youtube#playlistItem",
      "etag": "Lr5MBZwVL-oXsga3aB2m46Nb12U",
      "id": "UEx1aGw5VG5RUERDbldJaHlfS1NidEZ3WFZRbk52Z2ZTaC41MjE1MkI0OTQ2QzJGNzNG",
      "snippet": {
        "publishedAt": "2025-01-24T07:50:11Z",
        "channelId": "UC4QobU6STFB0P71PMvOGN5A",
        "title": "How YouTube Was Created ft. Founder Steve Chen",
        "description": "This episode takes us back to the earliest days of YouTube, as the founders explain why it was a longshot that succeeded against all odds. When cofounders Steve Chen, Chad Hurley and Jawed Karim left PayPal to start YouTube, it wasn\u2019t even clear that the nascent broadband infrastructure could support playing video in a browser. In a brief period until its acquisition by Google\u2014from its first incarnation as a video dating site to confronting daunting technical and legal challenges\u2014the early story of YouTube is an underdog tale of scrappy upstarts who ended up changing the world. \n\nHost: Roelof Botha, Sequoia Capital\nFeaturing: Steve Chen, Jawed Karim, Zahavah Levine, Colin Corbett, Yu Pan\n\nLearn more: https://www.cruciblemoments.com/episodes/youtube\n\n00:00 - Introduction\n02:23 - From PayPal to YouTube: The Genesis of a Digital Revolution\n05:24 - Solving the Online Video Challenge in 2005\n07:01 - From Dating Site to Video Sharing Platform\n09:11 - Overcoming Crickets to Sparking YouTube\u2019s Network Effect\n11:39 - How MySpace and Viral Clips Fueled YouTube\u2019s Early Growth\n14:17 - Securing Funding and Entering the Spotlight: YouTube\u2019s Rise in 2005\n16:05 - Scaling YouTube Amid Explosive Growth and Viral Success\n19:44 - YouTube\u2019s Shift to In-House Infrastructure\n21:35 - How YouTube Tackled Infrastructure Challenges \n23:51 - YouTube\u2019s Journey to Balancing Ads and Copyright Challenges\n28:48 - YouTube\u2019s Turning Point in the Fight for Copyright Agreements\n32:24 - The Pivotal Decision to Partner with Google\n35:25 - The Secretive Sale of YouTube to Google\n38:17 - The Acquisition That Secured YouTube\u2019s Future\n41:13 - Content ID: Cementing YouTube\u2019s Future with Copyright Holders\n43:10 - Building the Creator Economy and a Global Legacy",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "jawed",
        "playlistId": "PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
        "position": 0,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "lVI_J1cbFb4"
        },
        "videoOwnerChannelTitle": "Sequoia Capital",
        "videoOwnerChannelId": "UCWrF0oN6unbXrWsTN7RctTw"
      },
      "contentDetails": {
        "videoId": "lVI_J1cbFb4",
        "videoPublishedAt": "2024-12-05T10:00:50Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "48SdJl2f_Psbxp6cry5TvoTkQ8o",
      "id": "UEx1aGw5VG5RUERDbldJaHlfS1NidEZ3WFZRbk52Z2ZTaC41NkI0NEY2RDEwNTU3Q0M2",
      "snippet": {
        "publishedAt": "2020-04-28T07:33:20Z",
        "channelId": "UC4QobU6STFB0P71PMvOGN5A",
        "title": "r | p 2006: YouTube: From Concept to Hypergrowth - Jawed Karim",
        "description": "Less than two years after launch, YouTube has become one the most-visited destinations on the web. With more than 100 million videos served daily, it may be the fastest-growing entertainment website in the history of the World Wide Web. Jawed Karim will explain the thought process and the events that led to the development of YouTube.\n\nJawed Karim is the co-founder of the popular video sharing website YouTube. Karim attended the University of Illinois from 1997 until 2000, when he joined PayPal to become one of its first developers. He completed his remaining credits at UofI by correspondence and received a B.S. in CS in 2004. In 2005 Karim co-founded YouTube with two friends, co-developing the concept and product, and raising money from Sequoia Capital. He subsequently acted as an advisor to the company and is a graduate student in computer science at Stanford University and an investor in early-stage startups.\nJawed has a long history with ACM and Reflections Projections at UIUC. As a student in 1998, he presented a conference talk, \"Practical Graphics Programming,\" and in 1999, his team placed 2nd in MechMania.\nFor more information, please visit www.jawed.com.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "jawed",
        "playlistId": "PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
        "position": 1,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "XAJEXUNmP5M"
        },
        "videoOwnerChannelTitle": "Reflections Projections",
        "videoOwnerChannelId": "UCm5h-rixlNgYL1PoFPJjYog"
      },
      "contentDetails": {
        "videoId": "XAJEXUNmP5M",
        "videoPublishedAt": "2013-04-23T03:46:50Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    }
  ],
  "pageInfo": {
    "totalResults": 4,
    "resultsPerPage": 2
  }
}

=== ryn-cx/not-yt-dlapi/tests/_files/PlaylistItemsModel/PLHPTxTxtC0iZUB6K7RWdvB7bimNTqbL-O.json
{
  "kind": "youtube#playlistItemListResponse",
  "etag": "zTw6oVwNEHaUKqsBujMvQpOR3pY",
  "items": [
    {
      "kind": "youtube#playlistItem",
      "etag": "-iY1EV0yLEtc19q1gwnvZ9k_2Ao",
      "id": "UExIUFR4VHh0QzBpWlVCNks3UldkdkI3YmltTlRxYkwtTy5BNjBCMUFCN0Q5QzUyMjlG",
      "snippet": {
        "publishedAt": "2023-03-23T13:17:17Z",
        "channelId": "UClgRkhTL3_hImCAmdLfDE4g",
        "title": "Ein Sommer in Amalfi (Unplugged test movie by fake i18n partner)",
        "description": "Die Verlegerin Claudia Wesskampe ist gezwungen, ihren geplanten Urlaub abzusagen und stattdessen nach Italien zu reisen, um ihren Verlag zu retten. Begeistert ist sie davon nicht, denn Italien ist ihr viel zu klischeehaft. Aber ihr bester Autor hat seinen Vorschuss für andere Dinge verprasst, jedoch kein fertiges Buch geliefert und sich dann auch noch das Bein gebrochen. In Amalfi lernt Claudia Land und Leute kennen und erlebt so einige Überraschungen.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/kGysoYI-x8E/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/kGysoYI-x8E/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/kGysoYI-x8E/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/kGysoYI-x8E/sddefault.jpg",
            "width": 640,
            "height": 480
          }
        },
        "channelTitle": "YouTube Movies",
        "playlistId": "PLHPTxTxtC0iZUB6K7RWdvB7bimNTqbL-O",
        "position": 0,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "kGysoYI-x8E"
        },
        "videoOwnerChannelTitle": "Fake International Partner",
        "videoOwnerChannelId": "UC-EM-AldjtXCZBcXHGTg62g"
      },
      "contentDetails": {
        "videoId": "kGysoYI-x8E",
        "videoPublishedAt": "2022-08-06T08:24:37Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "KmtkJe7ZGy2H8iViisJpma0qTKY",
      "id": "UExIUFR4VHh0QzBpWlVCNks3UldkdkI3YmltTlRxYkwtTy4yMkNBN0M4QUJEQzYxMjA3",
      "snippet": {
        "publishedAt": "2023-03-23T13:17:17Z",
        "channelId": "UClgRkhTL3_hImCAmdLfDE4g",
        "title": "L'odyssée d'un trésor : L'or de Troie",
        "description": "Le documentaire suit les traces de l'or de Priam. Un voyage d'un siècle et demi depuis les plaines de Troie jusqu'aux voûtes d'un musée à Moscou.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/YalmgvxlZhY/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/YalmgvxlZhY/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/YalmgvxlZhY/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/YalmgvxlZhY/sddefault.jpg",
            "width": 640,
            "height": 480
          }
        },
        "channelTitle": "YouTube Movies",
        "playlistId": "PLHPTxTxtC0iZUB6K7RWdvB7bimNTqbL-O",
        "position": 1,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "YalmgvxlZhY"
        },
        "videoOwnerChannelTitle": "Fake International Partner",
        "videoOwnerChannelId": "UC-EM-AldjtXCZBcXHGTg62g"
      },
      "contentDetails": {
        "videoId": "YalmgvxlZhY",
        "videoPublishedAt": "2023-03-17T23:48:10Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "XG4tDUm37TEyqX1XvK6sMVQyCHM",
      "id": "UExIUFR4VHh0QzBpWlVCNks3UldkdkI3YmltTlRxYkwtTy4xQ0EyNTVGREQ1Nzk5MkVB",
      "snippet": {
        "publishedAt": "2023-03-23T13:17:17Z",
        "channelId": "UClgRkhTL3_hImCAmdLfDE4g",
        "title": "L'odyssée d'un trésor : L'or de Troie",
        "description": "Le documentaire suit les traces de l'or de Priam. Un voyage d'un siècle et demi depuis les plaines de Troie jusqu'aux voûtes d'un musée à Moscou.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/msjlIC_D0cA/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/msjlIC_D0cA/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/msjlIC_D0cA/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/msjlIC_D0cA/sddefault.jpg",
            "width": 640,
            "height": 480
          }
        },
        "channelTitle": "YouTube Movies",
        "playlistId": "PLHPTxTxtC0iZUB6K7RWdvB7bimNTqbL-O",
        "position": 2,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "msjlIC_D0cA"
        },
        "videoOwnerChannelTitle": "Fake International Partner",
        "videoOwnerChannelId": "UC-EM-AldjtXCZBcXHGTg62g"
      },
      "contentDetails": {
        "videoId": "msjlIC_D0cA",
        "videoPublishedAt": "2023-03-18T00:02:52Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    },
    {
      "kind": "youtube#playlistItem",
      "etag": "WZBNmTtO__9MIiNcMHee-W8xRO4",
      "id": "UExIUFR4VHh0QzBpWlVCNks3UldkdkI3YmltTlRxYkwtTy41MjA2QjlEREM3NTE0RkJG",
      "snippet": {
        "publishedAt": "2023-03-23T13:17:17Z",
        "channelId": "UClgRkhTL3_hImCAmdLfDE4g",
        "title": "Käfer und Prinzessin",
        "description": "Polizeiruf 110: Eine Kommune steht unter Schock. Der Chef Harald \"Harry\" Wacker wird tot aufgefunden - in der Sickergrube. Ein Unfall wird schnell ausgeschlossen, Harry wurde erdrosselt und dann in die Sickergrube geworfen.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/uLODe6b63MI/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/uLODe6b63MI/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/uLODe6b63MI/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/uLODe6b63MI/sddefault.jpg",
            "width": 640,
            "height": 480
          }
        },
        "channelTitle": "YouTube Movies",
        "playlistId": "PLHPTxTxtC0iZUB6K7RWdvB7bimNTqbL-O",
        "position": 3,
        "resourceId": {
          "kind": "youtube#video",
          "videoId": "uLODe6b63MI"
        },
        "videoOwnerChannelTitle": "Fake International Partner",
        "videoOwnerChannelId": "UC-EM-AldjtXCZBcXHGTg62g"
      },
      "contentDetails": {
        "videoId": "uLODe6b63MI",
        "videoPublishedAt": "2023-02-22T22:02:22Z"
      },
      "status": {
        "privacyStatus": "public"
      }
    }
  ],
  "pageInfo": {
    "totalResults": 4,
    "resultsPerPage": 50
  }
}
