=== ryn-cx/not-yt-dlapi/src/not_yt_dlapi/channel_feed/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"link": {"type": "array", "items": {"type": "object", "properties": {"rel": {"type": "string"}, "href": {"type": "string"}}, "required": ["href", "rel"]}}, "id": {"type": "string"}, "channelId": {"type": "string"}, "title": {"type": "string"}, "author": {"type": "object", "properties": {"name": {"type": "string"}, "uri": {"type": "string"}}, "required": ["name", "uri"]}, "published": {"type": "string", "format": "date-time"}, "entry": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "videoId": {"type": "string"}, "channelId": {"type": "string"}, "title": {"type": "string"}, "link": {"type": "array", "items": {"type": "object", "properties": {"rel": {"type": "string"}, "href": {"type": "string"}}, "required": ["href", "rel"]}}, "author": {"type": "object", "properties": {"name": {"type": "string"}, "uri": {"type": "string"}}, "required": ["name", "uri"]}, "published": {"type": "string", "format": "date-time"}, "updated": {"type": "string", "format": "date-time"}, "group": {"type": "object", "properties": {"title": {"type": "string"}, "content": {"type": "object", "properties": {"url": {"type": "string"}, "type": {"type": "string"}, "width": {"type": "string"}, "height": {"type": "string"}}, "required": ["height", "type", "url", "width"]}, "thumbnail": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "string"}, "height": {"type": "string"}}, "required": ["height", "url", "width"]}, "description": {"type": "string"}, "community": {"type": "object", "properties": {"starRating": {"type": "object", "properties": {"count": {"type": "string"}, "average": {"type": "string"}, "min": {"type": "string"}, "max": {"type": "string"}}, "required": ["average", "count", "max", "min"]}, "statistics": {"type": "object", "properties": {"views": {"type": "string"}}, "required": ["views"]}}, "required": ["starRating", "statistics"]}}, "required": ["community", "content", "description", "thumbnail", "title"]}}, "required": ["author", "channelId", "group", "id", "link", "published", "title", "updated", "videoId"]}}}, "required": ["author", "channelId", "entry", "id", "link", "published", "title"]}

=== ryn-cx/not-yt-dlapi/tests/_files/Channels/TestFeed/TestChannelId/UChqUTb7kYRX8-EiaN3XFrSQ.json
{
  "link": [
    {
      "rel": "self",
      "href": "http://www.youtube.com/feeds/videos.xml?channel_id=UChqUTb7kYRX8-EiaN3XFrSQ"
    },
    {
      "rel": "alternate",
      "href": "https://www.youtube.com/channel/UChqUTb7kYRX8-EiaN3XFrSQ"
    }
  ],
  "id": "yt:channel:hqUTb7kYRX8-EiaN3XFrSQ",
  "channelId": "hqUTb7kYRX8-EiaN3XFrSQ",
  "title": "Reuters",
  "author": {
    "name": "Reuters",
    "uri": "https://www.youtube.com/channel/UChqUTb7kYRX8-EiaN3XFrSQ"
  },
  "published": "2007-03-01T20:50:17+00:00",
  "entry": [
    {
      "id": "yt:video:XLawncfQPjU",
      "videoId": "XLawncfQPjU",
      "channelId": "UChqUTb7kYRX8-EiaN3XFrSQ",
      "title": "LIVE: South Korea conducts nationwide civil defense drill",
      "link": [
        {
          "rel": "alternate",
          "href": "https://www.youtube.com/watch?v=XLawncfQPjU"
        }
      ],
      "author": {
        "name": "Reuters",
        "uri": "https://www.youtube.com/channel/UChqUTb7kYRX8-EiaN3XFrSQ"
      },
      "published": "2026-08-20T04:55:05+00:00",
      "updated": "2026-08-20T04:56:20+00:00",
      "group": {
        "title": "LIVE: South Korea conducts nationwide civil defense drill",
        "content": {
          "url": "https://www.youtube.com/v/XLawncfQPjU?version=3",
          "type": "application/x-shockwave-flash",
          "width": "640",
          "height": "390"
        },
        "thumbnail": {
          "url": "https://i1.ytimg.com/vi/XLawncfQPjU/hqdefault.jpg",
          "width": "480",
          "height": "360"
        },
        "description": "South Korea conducts a nationwide civil defense drill in case of an air raid. Pedestrians are to move to shelters or underground space, and traffic is to be halted on some roads during the drill which is scheduled to be conducted for 20 minutes from 2 p.m. local time.\n\n#civildefensedrill #airraid #shelter #underground #SouthKorea #live #Reuters #news\n\nKeep up with the latest news from around the world: https://www.reuters.com/",
        "community": {
          "starRating": {
            "count": "7",
            "average": "5.00",
            "min": "1",
            "max": "5"
          },
          "statistics": {
            "views": "140"
          }
        }
      }
    },
    {
      "id": "yt:video:r39i7_LTPOA",
      "videoId": "r39i7_LTPOA",
      "channelId": "UChqUTb7kYRX8-EiaN3XFrSQ",
      "title": "LIVE: World Robot Conference in Beijing",
      "link": [
        {
          "rel": "alternate",
          "href": "https://www.youtube.com/watch?v=r39i7_LTPOA"
        }
      ],
      "author": {
        "name": "Reuters",
        "uri": "https://www.youtube.com/channel/UChqUTb7kYRX8-EiaN3XFrSQ"
      },
      "published": "2026-08-20T02:05:07+00:00",
      "updated": "2026-08-20T04:40:59+00:00",
      "group": {
        "title": "LIVE: World Robot Conference in Beijing",
        "content": {
          "url": "https://www.youtube.com/v/r39i7_LTPOA?version=3",
          "type": "application/x-shockwave-flash",
          "width": "640",
          "height": "390"
        },
        "thumbnail": {
          "url": "https://i3.ytimg.com/vi/r39i7_LTPOA/hqdefault.jpg",
          "width": "480",
          "height": "360"
        },
        "description": "The 2026 World Robot Conference is on in Beijing, featuring more than 300 exhibiting companies and over 2,000 exhibits.\n\n#WorldRobotConference #WRC #robotics #robots #tech #technology#Beijing #China #live #Reuters #news\n\nKeep up with the latest news from around the world: https://www.reuters.com/",
        "community": {
          "starRating": {
            "count": "31",
            "average": "5.00",
            "min": "1",
            "max": "5"
          },
          "statistics": {
            "views": "1164"
          }
        }
      }
    },
    {
      "id": "yt:video:734_DaqYynI",
      "videoId": "734_DaqYynI",
      "channelId": "UChqUTb7kYRX8-EiaN3XFrSQ",
      "title": "Cancer vaccine raising new treatment hope",
      "link": [
        {
          "rel": "alternate",
          "href": "https://www.youtube.com/shorts/734_DaqYynI"
        }
      ],
      "author": {
        "name": "Reuters",
        "uri": "https://www.youtube.com/channel/UChqUTb7kYRX8-EiaN3XFrSQ"
      },
      "published": "2026-08-20T01:53:22+00:00",
      "updated": "2026-08-20T02:00:31+00:00",
      "group": {
        "title": "Cancer vaccine raising new treatment hope",
        "content": {
          "url": "https://www.youtube.com/v/734_DaqYynI?version=3",
          "type": "application/x-shockwave-flash",
          "width": "640",
          "height": "390"
        },
        "thumbnail": {
          "url": "https://i4.ytimg.com/vi/734_DaqYynI/hqdefault.jpg",
          "width": "480",
          "height": "360"
        },
        "description": "Moderna and Merck said that a personalized mRNA cancer vaccine reduced the risk of recurrence and spread of melanoma in a late-stage trial, a major success in a new field of cancer treatment that sent Moderna's shares surging as much as 160%. Michele Gershberg has more.\n\n#melanoma #cancer #vaccine #moderna #merck #News #Reuters #Newsfeed \n\nRead the story here: https://www.reuters.com/legal/litigation/merck-moderna-say-melanoma-skin-cancer-vaccine-meets-goals-large-trial-2026-08-19/\n\n\ud83d\udc49 Subscribe: https://reut.rs/4b8fRGn\n\nKeep up with the latest news from around the world: https://www.reuters.com/\nFollow Reuters on Facebook: https://www.facebook.com/Reuters\nFollow Reuters on X: https://twitter.com/Reuters\nFollow Reuters on Instagram: https://www.instagram.com/reuters/?hl=en",
        "community": {
          "starRating": {
            "count": "33",
            "average": "5.00",
            "min": "1",
            "max": "5"
          },
          "statistics": {
            "views": "476"
          }
        }
      }
    },
    {
      "id": "yt:video:Y1oQCXs4NSk",
      "videoId": "Y1oQCXs4NSk",
      "channelId": "UChqUTb7kYRX8-EiaN3XFrSQ",
      "title": "Can Ukraine hold elections while at war?",
      "link": [
        {
          "rel": "alternate",
          "href": "https://www.youtube.com/shorts/Y1oQCXs4NSk"
        }
      ],
      "author": {
        "name": "Reuters",
        "uri": "https://www.youtube.com/channel/UChqUTb7kYRX8-EiaN3XFrSQ"
      },
      "published": "2026-08-20T01:00:01+00:00",
      "updated": "2026-08-20T04:56:59+00:00",
      "group": {
        "title": "Can Ukraine hold elections while at war?",
        "content": {
          "url": "https://www.youtube.com/v/Y1oQCXs4NSk?version=3",
          "type": "application/x-shockwave-flash",
          "width": "640",
          "height": "390"
        },
        "thumbnail": {
          "url": "https://i2.ytimg.com/vi/Y1oQCXs4NSk/hqdefault.jpg",
          "width": "480",
          "height": "360"
        },
        "description": "Ukraine's ousted defense minister Mykhailo Fedorov called for wartime elections in a bombshell address on August 18, arguing the government was failing to tackle corruption. Reuters Ukraine Bureau Chief Dan Flynn explains the obstacles that would need to be overcome for Ukraine to hold wartime elections.\n\n#ukraine #election #mykhailofedorov #russiaukrainewar #volodymyrzelenskiy #News #Reuters #Newsfeed \n\nRead the story here: https://www.reuters.com/world/europe/ukraine-anti-graft-agencies-investigate-group-involving-presidential-officials-2026-08-19/\n\n\ud83d\udc49 Subscribe: https://reut.rs/4b8fRGn\n\nKeep up with the latest news from around the world: https://www.reuters.com/\nFollow Reuters on Facebook: https://www.facebook.com/Reuters\nFollow Reuters on X: https://twitter.com/Reuters\nFollow Reuters on Instagram: https://www.instagram.com/reuters/?hl=en",
        "community": {
          "starRating": {
            "count": "39",
            "average": "5.00",
            "min": "1",
            "max": "5"
          },
          "statistics": {
            "views": "863"
          }
        }
      }
    },
    {
      "id": "yt:video:cicJtPpC4UI",
      "videoId": "cicJtPpC4UI",
      "channelId": "UChqUTb7kYRX8-EiaN3XFrSQ",
      "title": "'Peaky Blinders' experience lets fans enter show's world",
      "link": [
        {
          "rel": "alternate",
          "href": "https://www.youtube.com/watch?v=cicJtPpC4UI"
        }
      ],
      "author": {
        "name": "Reuters",
        "uri": "https://www.youtube.com/channel/UChqUTb7kYRX8-EiaN3XFrSQ"
      },
      "published": "2026-08-20T00:22:29+00:00",
      "updated": "2026-08-20T00:55:11+00:00",
      "group": {
        "title": "'Peaky Blinders' experience lets fans enter show's world",
        "content": {
          "url": "https://www.youtube.com/v/cicJtPpC4UI?version=3",
          "type": "application/x-shockwave-flash",
          "width": "640",
          "height": "390"
        },
        "thumbnail": {
          "url": "https://i4.ytimg.com/vi/cicJtPpC4UI/hqdefault.jpg",
          "width": "480",
          "height": "360"
        },
        "description": "A new 'Peaky Blinders' interactive experience offers the British crime drama's fans a chance to step into the gritty world of Cillian Murphy's antihero Thomas Shelby and his early 20th-century Birmingham gang.\n\n#News #Reuters #Newsfeed #world #entertainment #PeakyBlinders #CillianMurphy #ThomasShelby \n\n\ud83d\udc49 Subscribe: https://reut.rs/4b8fRGn\n\nKeep up with the latest news from around the world: https://www.reuters.com/\nFollow Reuters on Facebook: https://www.facebook.com/Reuters\nFollow Reuters on X: https://twitter.com/Reuters\nFollow Reuters on Instagram: https://www.instagram.com/reuters/?hl=en",
        "community": {
          "starRating": {
            "count": "9",
            "average": "5.00",
            "min": "1",
            "max": "5"
          },
          "statistics": {
            "views": "405"
          }
        }
      }
    },
    {
      "id": "yt:video:PFHWqhfFrs4",
