=== ryn-cx/not-yt-dlapi/src/not_yt_dlapi/channels/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "pageInfo": {"type": "object", "properties": {"totalResults": {"type": "integer"}, "resultsPerPage": {"type": "integer"}}, "required": ["resultsPerPage", "totalResults"]}, "items": {"type": "array", "items": {"type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "id": {"type": "string"}, "snippet": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}, "customUrl": {"type": "string"}, "publishedAt": {"type": "string", "format": "date-time"}, "thumbnails": {"type": "object", "properties": {"default": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "medium": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "high": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "required": ["default", "high", "medium"]}, "localized": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "country": {"type": "string"}, "defaultLanguage": {"type": "string"}}, "required": ["description", "localized", "publishedAt", "thumbnails", "title"]}, "contentDetails": {"type": "object", "properties": {"relatedPlaylists": {"type": "object", "properties": {"likes": {"type": "string"}, "uploads": {"type": "string"}}, "required": ["likes", "uploads"]}}, "required": ["relatedPlaylists"]}, "statistics": {"type": "object", "properties": {"viewCount": {"type": "string"}, "subscriberCount": {"type": "string"}, "hiddenSubscriberCount": {"type": "boolean"}, "videoCount": {"type": "string"}}, "required": ["hiddenSubscriberCount", "subscriberCount", "videoCount", "viewCount"]}, "status": {"type": "object", "properties": {"privacyStatus": {"type": "string"}, "isLinked": {"type": "boolean"}, "longUploadsStatus": {"type": "string"}, "madeForKids": {"type": "boolean"}}, "required": ["isLinked", "longUploadsStatus", "privacyStatus"]}, "brandingSettings": {"type": "object", "properties": {"channel": {"type": "object", "properties": {"title": {"type": "string"}, "keywords": {"type": "string"}, "unsubscribedTrailer": {"type": "string"}, "country": {"type": "string"}, "description": {"type": "string"}, "defaultLanguage": {"type": "string"}}, "required": ["title"]}, "image": {"type": "object", "properties": {"bannerExternalUrl": {"type": "string"}}, "required": ["bannerExternalUrl"]}}, "required": ["channel"]}, "contentOwnerDetails": {"type": "object"}, "topicDetails": {"type": "object", "properties": {"topicIds": {"type": "array", "items": {"type": "string"}}, "topicCategories": {"type": "array", "items": {"type": "string"}}}, "required": ["topicCategories", "topicIds"]}, "localizations": {"type": "object", "properties": {"ne": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "bn": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "hy": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ru": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "es-US": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "hr": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "hi": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "pa": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "en-IN": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "eu": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "pt-PT": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "hu": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "sk": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ta": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "lo": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "sq": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ja": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "km": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "af": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "es": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ur": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "et": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "iw": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "sr": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "fi": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "da": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "zh-TW": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "de": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "cs": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "bs": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "as": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "my": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "sl": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "it": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "id": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "be": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "pl": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "en-GB": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "zh-HK": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "th": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "is": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "fr": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ro": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "am": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "no": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "en": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "fil": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "nl": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "fa": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "bg": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "sr-Latn": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "mn": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "az": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "kn": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "pt": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "sw": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "tr": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "sv": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ca": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ko": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "or": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ml": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "zh-CN": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "mr": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ky": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "zu": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "fr-CA": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "es-419": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "si": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ka": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "gu": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ar": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "gl": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "vi": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "uk": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "lv": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "mk": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "kk": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ms": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "lt": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "te": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "el": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "uz": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "zh": {"type": "object", "properties": {"description": {"type": "string"}}, "required": ["description"]}, "pt-BR": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "en_US": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}}}}, "required": ["brandingSettings", "contentDetails", "contentOwnerDetails", "etag", "id", "kind", "snippet", "statistics", "status"]}}}, "required": ["etag", "kind", "pageInfo"]}

=== ryn-cx/not-yt-dlapi/tests/_files/ChannelsModel/UC4QobU6STFB0P71PMvOGN5A.json
{
  "kind": "youtube#channelListResponse",
  "etag": "GXGhClscuXS4LYwcSBTU7p1pHlw",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 5
  },
  "items": [
    {
      "kind": "youtube#channel",
      "etag": "GaAZUP5nUdxwknGHVmf_UKyMzq0",
      "id": "UC4QobU6STFB0P71PMvOGN5A",
      "snippet": {
        "title": "jawed",
        "description": "",
        "customUrl": "@jawed",
        "publishedAt": "2005-04-24T03:20:54Z",
        "thumbnails": {
          "default": {
            "url": "https://yt3.ggpht.com/uI3VE4PVqvCy0xnWLqMJnEzyBUm3T8VHOCp4ee-1RxdHqKXCdUE_qXYQnpf9AfuEoIPactVyDhM=s88-c-k-c0x00ffffff-no-rj",
            "width": 88,
            "height": 88
          },
          "medium": {
            "url": "https://yt3.ggpht.com/uI3VE4PVqvCy0xnWLqMJnEzyBUm3T8VHOCp4ee-1RxdHqKXCdUE_qXYQnpf9AfuEoIPactVyDhM=s240-c-k-c0x00ffffff-no-rj",
            "width": 240,
            "height": 240
          },
          "high": {
            "url": "https://yt3.ggpht.com/uI3VE4PVqvCy0xnWLqMJnEzyBUm3T8VHOCp4ee-1RxdHqKXCdUE_qXYQnpf9AfuEoIPactVyDhM=s800-c-k-c0x00ffffff-no-rj",
            "width": 800,
            "height": 800
          }
        },
        "localized": {
          "title": "jawed",
          "description": ""
        },
        "country": "US"
      },
      "contentDetails": {
        "relatedPlaylists": {
          "likes": "",
          "uploads": "UU4QobU6STFB0P71PMvOGN5A"
        }
      },
      "statistics": {
        "viewCount": "405753898",
        "subscriberCount": "6430000",
        "hiddenSubscriberCount": false,
        "videoCount": "1"
      },
      "status": {
        "privacyStatus": "public",
        "isLinked": true,
        "longUploadsStatus": "longUploadsUnspecified",
        "madeForKids": false
      },
      "brandingSettings": {
        "channel": {
          "title": "jawed",
          "keywords": "\"me at the zoo\" \"jawed karim\" \"first youtube video\"",
          "unsubscribedTrailer": "jNQXAC9IVRw",
          "country": "US"
        },
        "image": {
          "bannerExternalUrl": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg"
        }
      },
      "contentOwnerDetails": {}
    }
  ]
}

=== ryn-cx/not-yt-dlapi/tests/_files/Channels/TestList/TestChannelUsername/MrBeast.json
{
  "kind": "youtube#channelListResponse",
  "etag": "mLRtk7Vq6DLxNhbZb7gWuWHoUtQ",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 5
  },
  "items": [
    {
      "kind": "youtube#channel",
      "etag": "Isj8oI6j8iocIXWJ_ZRS_V2Qboo",
      "id": "UCgoFStVyEsm8tBZP5NC-aBQ",
      "snippet": {
        "title": "MrBeast",
        "description": "",
        "customUrl": "@user-uv1rl3kz5x",
        "publishedAt": "2006-03-11T18:48:11Z",
        "thumbnails": {
          "default": {
            "url": "https://yt3.ggpht.com/ytc/AIdro_n3Ch8N2rxItVnYnvvZ43mSsKzCIJ2LsYFEcn__vgelkVY=s88-c-k-c0x00ffffff-no-rj",
            "width": 88,
            "height": 88
          },
          "medium": {
            "url": "https://yt3.ggpht.com/ytc/AIdro_n3Ch8N2rxItVnYnvvZ43mSsKzCIJ2LsYFEcn__vgelkVY=s240-c-k-c0x00ffffff-no-rj",
            "width": 240,
            "height": 240
          },
          "high": {
            "url": "https://yt3.ggpht.com/ytc/AIdro_n3Ch8N2rxItVnYnvvZ43mSsKzCIJ2LsYFEcn__vgelkVY=s800-c-k-c0x00ffffff-no-rj",
            "width": 800,
            "height": 800
          }
        },
        "localized": {
          "title": "MrBeast",
          "description": ""
        }
      },
      "contentDetails": {
        "relatedPlaylists": {
          "likes": "",
          "uploads": "UUgoFStVyEsm8tBZP5NC-aBQ"
        }
      },
      "statistics": {
        "viewCount": "78232",
        "subscriberCount": "2090",
        "hiddenSubscriberCount": false,
        "videoCount": "3"
      },
      "topicDetails": {
        "topicIds": [
          "/m/02ntfj",
          "/m/0bzvm2",
          "/m/0403l3g",
          "/m/025zzc"
        ],
        "topicCategories": [
          "https://en.wikipedia.org/wiki/Action-adventure_game",
          "https://en.wikipedia.org/wiki/Video_game_culture",
          "https://en.wikipedia.org/wiki/Role-playing_video_game",
          "https://en.wikipedia.org/wiki/Action_game"
        ]
      },
      "status": {
        "privacyStatus": "public",
        "isLinked": true,
        "longUploadsStatus": "longUploadsUnspecified"
      },
      "brandingSettings": {
        "channel": {
          "title": "MrBeast"
        }
      },
      "contentOwnerDetails": {}
    }
  ]
}

=== ryn-cx/not-yt-dlapi/tests/_files/Channels/TestList/TestChannelHandle/@Google.json
{
  "kind": "youtube#channelListResponse",
  "etag": "HQWeUG1ct8oxGaoLWle9yVBfqpE",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 5
  },
  "items": [
    {
      "kind": "youtube#channel",
      "etag": "NFeIDr1WpimmMeNH7d3PRv0drc4",
      "id": "UCK8sQmJBp8GCxrOtXWBpyEA",
      "snippet": {
        "title": "Google",
        "description": "Here to help. \n\nReimagining how AI can make your life better and help you explore your creativity, connect with the world, and discover new possibilities. Browse our latest product demos, unboxings, developer roundtables, podcasts, tips, tricks and more. Subscribe for the latest product updates, innovations, and a peek inside the magic of Google.\n",
        "customUrl": "@google",
        "publishedAt": "2005-09-18T22:37:10Z",
        "thumbnails": {
          "default": {
            "url": "https://yt3.ggpht.com/bAseQlKvNmjdLQrvYWm_q3QDp8C8YKyYI-nYJewgOkPi0JU1_3X9oFgjrEdzkOlXzLGFxFbnsw=s88-c-k-c0x00ffffff-no-rj",
            "width": 88,
            "height": 88
          },
          "medium": {
            "url": "https://yt3.ggpht.com/bAseQlKvNmjdLQrvYWm_q3QDp8C8YKyYI-nYJewgOkPi0JU1_3X9oFgjrEdzkOlXzLGFxFbnsw=s240-c-k-c0x00ffffff-no-rj",
            "width": 240,
            "height": 240
          },
          "high": {
            "url": "https://yt3.ggpht.com/bAseQlKvNmjdLQrvYWm_q3QDp8C8YKyYI-nYJewgOkPi0JU1_3X9oFgjrEdzkOlXzLGFxFbnsw=s800-c-k-c0x00ffffff-no-rj",
            "width": 800,
            "height": 800
          }
        },
        "localized": {
          "title": "Google",
          "description": "Here to help. \n\nReimagining how AI can make your life better and help you explore your creativity, connect with the world, and discover new possibilities. Browse our latest product demos, unboxings, developer roundtables, podcasts, tips, tricks and more. Subscribe for the latest product updates, innovations, and a peek inside the magic of Google.\n"
        }
      },
      "contentDetails": {
        "relatedPlaylists": {
          "likes": "",
          "uploads": "UUK8sQmJBp8GCxrOtXWBpyEA"
        }
      },
      "statistics": {
        "viewCount": "6741495118",
        "subscriberCount": "14500000",
        "hiddenSubscriberCount": false,
        "videoCount": "2757"
      },
      "topicDetails": {
        "topicIds": [
          "/m/06ntj",
          "/m/07c1v",
          "/m/019_rr"
        ],
        "topicCategories": [
          "https://en.wikipedia.org/wiki/Sport",
          "https://en.wikipedia.org/wiki/Technology",
          "https://en.wikipedia.org/wiki/Lifestyle_(sociology)"
        ]
      },
      "status": {
        "privacyStatus": "public",
        "isLinked": true,
        "longUploadsStatus": "longUploadsUnspecified",
        "madeForKids": false
      },
      "brandingSettings": {
        "channel": {
          "title": "Google",
          "description": "Here to help. \n\nReimagining how AI can make your life better and help you explore your creativity, connect with the world, and discover new possibilities. Browse our latest product demos, unboxings, developer roundtables, podcasts, tips, tricks and more. Subscribe for the latest product updates, innovations, and a peek inside the magic of Google.\n",
          "keywords": "Google Technology Science Android \"Google app\" \"Google Doodles\" \"Google Gemini\" \"Gemini AI\" \"Google AI\" Google Android \"Google Chrome\" \"Google Search\" \"Google AI\" YouTube \"Google Play Store\" AI \"Artificial Intelligence\" Tech Technology Innovation \"Machine Learning\" \"Quantum Computing\" \"Google I/O\" \"Made by Google\" \"Google Doodle\" \"Team Google\" Explained How-to Tutorial \"Google Tips\" \"Tech Tips\" \"Google Help\" \"Google products\" \"Google updates\" NotebookLM NanoBanana Veo \"Gen AI\" Pixel unboxing",
          "trackingAnalyticsAccountId": "UA-7001471-1",
          "unsubscribedTrailer": "YSKzyVOQmuA"
        },
        "image": {
          "bannerExternalUrl": "https://yt3.googleusercontent.com/CCRE_EIc_j1eMz11icjGP-QXRMtUFg02CDqBHmuD6pSfD0c7BlPEOWo2_gTy2CGMEQl_4uyV_Q"
        }
      },
      "contentOwnerDetails": {}
    }
  ]
}
