=== ryn-cx/not-yt-dlapi/src/not_yt_dlapi/videos/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "items": {"type": "array", "items": {"type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "id": {"type": "string"}, "snippet": {"type": "object", "properties": {"publishedAt": {"type": "string", "format": "date-time"}, "channelId": {"type": "string"}, "title": {"type": "string"}, "description": {"type": "string"}, "thumbnails": {"type": "object", "properties": {"default": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "medium": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "high": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "standard": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "maxres": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "fhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "qhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "uhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "required": ["default", "high", "medium"]}, "channelTitle": {"type": "string"}, "categoryId": {"type": "string"}, "liveBroadcastContent": {"type": "string"}, "defaultLanguage": {"type": "string"}, "localized": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "defaultAudioLanguage": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}}, "required": ["categoryId", "channelId", "channelTitle", "defaultLanguage", "description", "liveBroadcastContent", "localized", "publishedAt", "thumbnails", "title"]}, "contentDetails": {"type": "object", "properties": {"dimension": {"type": "string", "format": "duration"}, "definition": {"type": "string"}, "caption": {"type": "string"}, "licensedContent": {"type": "boolean"}, "contentRating": {"type": "object"}, "projection": {"type": "string"}, "duration": {"type": "string", "format": "duration"}, "regionRestriction": {"type": "object", "properties": {"allowed": {"type": "array", "items": {"type": "string"}}, "blocked": {"type": "array", "items": {"type": "string"}}}}}, "required": ["caption", "contentRating", "definition", "dimension", "licensedContent", "projection"]}, "status": {"type": "object", "properties": {"uploadStatus": {"type": "string"}, "privacyStatus": {"type": "string"}, "license": {"type": "string"}, "embeddable": {"type": "boolean"}, "publicStatsViewable": {"type": "boolean"}, "madeForKids": {"type": "boolean"}}, "required": ["embeddable", "license", "madeForKids", "privacyStatus", "publicStatsViewable", "uploadStatus"]}, "statistics": {"type": "object", "properties": {"viewCount": {"type": "string"}, "likeCount": {"type": "string"}, "favoriteCount": {"type": "string"}, "commentCount": {"type": "string"}}, "required": ["favoriteCount"]}, "player": {"type": "object", "properties": {"embedHtml": {"type": "string"}}, "required": ["embedHtml"]}, "topicDetails": {"type": "object", "properties": {"topicCategories": {"type": "array", "items": {"type": "string"}}}, "required": ["topicCategories"]}, "recordingDetails": {"type": "object", "properties": {"locationDescription": {"type": "string"}, "location": {"type": "object", "properties": {"latitude": {"type": "number"}, "longitude": {"type": "number"}, "altitude": {"type": "integer"}}, "required": ["altitude", "latitude", "longitude"]}, "recordingDate": {"type": "string", "format": "date-time"}}}, "liveStreamingDetails": {"type": "object", "properties": {"scheduledStartTime": {"type": "string", "format": "date-time"}, "activeLiveChatId": {"type": "string"}, "actualStartTime": {"type": "string", "format": "date-time"}, "actualEndTime": {"type": "string", "format": "date-time"}}}, "localizations": {"type": "object", "properties": {"en-US": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "en": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "und": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "hi": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ko": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ta": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "id": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "pa": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "es-US": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "nl-NL": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description"]}, "pl": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "te": {"type": "object", "properties": {"description": {"type": "string"}, "title": {"type": "string"}}, "required": ["description"]}, "uk": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "it": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "iw": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ml": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "fr-FR": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "de-DE": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ru": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description"]}, "bn": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "pt-BR": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ja": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ar": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "de": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "en-GB": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}}}, "paidProductPlacementDetails": {"type": "object", "properties": {"hasPaidProductPlacement": {"type": "boolean"}}, "required": ["hasPaidProductPlacement"]}}, "required": ["contentDetails", "etag", "id", "kind", "localizations", "paidProductPlacementDetails", "player", "recordingDetails", "snippet", "statistics", "status"]}}, "pageInfo": {"type": "object", "properties": {"totalResults": {"type": "integer"}, "resultsPerPage": {"type": "integer"}}, "required": ["resultsPerPage", "totalResults"]}}, "required": ["etag", "items", "kind", "pageInfo"]}

=== ryn-cx/not-yt-dlapi/tests/_files/VideosModel/6JTFYuloLFM.json
{
  "kind": "youtube#videoListResponse",
  "etag": "qsRZtlmddd7oAnQBeUcuQpsgGB8",
  "items": [
    {
      "kind": "youtube#video",
      "etag": "8DFt7cdxjnFvR8cEJEvnfnKzncc",
      "id": "6JTFYuloLFM",
      "snippet": {
        "publishedAt": "2024-10-01T04:02:04Z",
        "channelId": "UCuVPpxrm2VAgpH3Ktln4HXg",
        "title": "The Tell Tale Tummy /  A Little Help",
        "description": "The Tell-Tale Tummy: Share breaks Grumpy’s Cloud Express invention and tries to hide that she did it. Feeling the guilt, Shares learns about her conscience as it tries to tell her something through her tummy. A Little Help:  Grumpy has too much to handle in preparation for the Rainbow Night celebration, but he won’t ask for help. When Grizzle needs help of his own, Grumpy’s is the first to offer the villain a hand—and THAT makes him take a look at his own situation",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/6JTFYuloLFM/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/6JTFYuloLFM/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/6JTFYuloLFM/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/6JTFYuloLFM/sddefault.jpg",
            "width": 640,
            "height": 480
          }
        },
        "channelTitle": "YouTube Movies",
        "categoryId": "43",
        "liveBroadcastContent": "none",
        "defaultLanguage": "und",
        "localized": {
          "title": "The Tell Tale Tummy /  A Little Help",
          "description": "The Tell-Tale Tummy: Share breaks Grumpy’s Cloud Express invention and tries to hide that she did it. Feeling the guilt, Shares learns about her conscience as it tries to tell her something through her tummy. A Little Help:  Grumpy has too much to handle in preparation for the Rainbow Night celebration, but he won’t ask for help. When Grizzle needs help of his own, Grumpy’s is the first to offer the villain a hand—and THAT makes him take a look at his own situation"
        },
        "defaultAudioLanguage": "en"
      },
      "contentDetails": {
        "duration": "PT21M17S",
        "dimension": "2d",
        "definition": "sd",
        "caption": "true",
        "licensedContent": true,
        "regionRestriction": {
          "allowed": [
            "US"
          ]
        },
        "contentRating": {},
        "projection": "rectangular"
      },
      "status": {
        "uploadStatus": "processed",
        "privacyStatus": "public",
        "license": "youtube",
        "embeddable": true,
        "publicStatsViewable": true,
        "madeForKids": true
      },
      "statistics": {
        "likeCount": "1950",
        "favoriteCount": "0",
        "commentCount": "0"
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"480\" height=\"360\" src=\"//www.youtube.com/embed/6JTFYuloLFM\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      },
      "topicDetails": {
        "topicCategories": [
          "https://en.wikipedia.org/wiki/Entertainment",
          "https://en.wikipedia.org/wiki/Film",
          "https://en.wikipedia.org/wiki/Television_program"
        ]
      },
      "recordingDetails": {},
      "localizations": {
        "und": {
          "title": "The Tell Tale Tummy /  A Little Help",
          "description": "The Tell-Tale Tummy: Share breaks Grumpy’s Cloud Express invention and tries to hide that she did it. Feeling the guilt, Shares learns about her conscience as it tries to tell her something through her tummy. A Little Help:  Grumpy has too much to handle in preparation for the Rainbow Night celebration, but he won’t ask for help. When Grizzle needs help of his own, Grumpy’s is the first to offer the villain a hand—and THAT makes him take a look at his own situation"
        }
      },
      "paidProductPlacementDetails": {
        "hasPaidProductPlacement": false
      }
    }
  ],
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 1
  }
}

=== ryn-cx/not-yt-dlapi/tests/_files/VideosModel/zKQGAv8gtBA.json
{
  "kind": "youtube#videoListResponse",
  "etag": "h6XlFqpYXVyTGXooOsUmekAOPto",
  "items": [
    {
      "kind": "youtube#video",
      "etag": "UT3l_-nDethmeZVGXXWGU_WZuu4",
      "id": "zKQGAv8gtBA",
      "snippet": {
        "publishedAt": "2019-07-26T17:02:45Z",
        "channelId": "UCuVPpxrm2VAgpH3Ktln4HXg",
        "title": "Super Size Me",
        "description": "Winner at Sundance, director Morgan Spurlock's social experiment in fast-food gastronomy sees him attempting to subsist uniquely on food from the McDonald's menu for an entire month. In the process his weight balloons, his energy level plummets and he experiences all sorts of unexpected -- and terrifying -- side effects.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/zKQGAv8gtBA/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/zKQGAv8gtBA/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/zKQGAv8gtBA/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/zKQGAv8gtBA/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/zKQGAv8gtBA/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "YouTube Movies",
        "categoryId": "30",
        "liveBroadcastContent": "none",
        "defaultLanguage": "en",
        "localized": {
          "title": "Super Size Me",
          "description": "Winner at Sundance, director Morgan Spurlock's social experiment in fast-food gastronomy sees him attempting to subsist uniquely on food from the McDonald's menu for an entire month. In the process his weight balloons, his energy level plummets and he experiences all sorts of unexpected -- and terrifying -- side effects."
        },
        "defaultAudioLanguage": "en"
      },
      "contentDetails": {
        "duration": "PT1H39M52S",
        "dimension": "2d",
        "definition": "hd",
        "caption": "true",
        "licensedContent": true,
        "regionRestriction": {
          "allowed": [
            "US"
          ]
        },
        "contentRating": {},
        "projection": "rectangular"
      },
      "status": {
        "uploadStatus": "processed",
        "privacyStatus": "public",
        "license": "youtube",
        "embeddable": true,
        "publicStatsViewable": true,
        "madeForKids": false
      },
      "statistics": {
        "likeCount": "114041",
        "favoriteCount": "0",
        "commentCount": "30107"
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"480\" height=\"270\" src=\"//www.youtube.com/embed/zKQGAv8gtBA\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      },
      "topicDetails": {
        "topicCategories": [
          "https://en.wikipedia.org/wiki/Entertainment",
          "https://en.wikipedia.org/wiki/Film",
          "https://en.wikipedia.org/wiki/Television_program"
        ]
      },
      "recordingDetails": {},
      "localizations": {
        "en": {
          "title": "Super Size Me",
          "description": "Winner at Sundance, director Morgan Spurlock's social experiment in fast-food gastronomy sees him attempting to subsist uniquely on food from the McDonald's menu for an entire month. In the process his weight balloons, his energy level plummets and he experiences all sorts of unexpected -- and terrifying -- side effects."
        }
      },
      "paidProductPlacementDetails": {
        "hasPaidProductPlacement": false
      }
    }
  ],
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 1
  }
}

=== ryn-cx/not-yt-dlapi/tests/_files/Videos/TestList/g1eZjGhN8oo.json
{
  "kind": "youtube#videoListResponse",
  "etag": "XYe8aoCh5igxxQr6K66B92TWnqM",
  "items": [
    {
      "kind": "youtube#video",
      "etag": "ic_aWMYWLM0qA7mIFclqT9cO8OY",
      "id": "g1eZjGhN8oo",
      "snippet": {
        "publishedAt": "2012-06-29T19:12:25Z",
        "channelId": "UCYoEbMFACdvkquYH5h31RNA",
        "title": "The Graduate",
        "description": "Nominated for 7 Academy Awards and Winner for Best Directing, this groundbreaking film classic launched the career of two-time Oscar Winner Dustin Hoffman. During a party given by his parents to celebrate his graduation, Benjamin Braddock (Hoffman) is seduced by the sexy Mrs. Robinson (Anne Bancroft), the wife of his father's business partner and closes friends. Although Benjamin is shy and inexperienced, they have an affair. But then, when Benjamin falls in love with Mrs. Robinson's daughter, Elaine (Katharine Ross), a jealous and angry Mrs. Robinson does everything in her power to keep the young couple apart.",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/g1eZjGhN8oo/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/g1eZjGhN8oo/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/g1eZjGhN8oo/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/g1eZjGhN8oo/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/g1eZjGhN8oo/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "YouTube Movies",
        "categoryId": "30",
        "liveBroadcastContent": "none",
        "defaultLanguage": "und",
        "localized": {
          "title": "The Graduate",
          "description": "Nominated for 7 Academy Awards and Winner for Best Directing, this groundbreaking film classic launched the career of two-time Oscar Winner Dustin Hoffman. During a party given by his parents to celebrate his graduation, Benjamin Braddock (Hoffman) is seduced by the sexy Mrs. Robinson (Anne Bancroft), the wife of his father's business partner and closes friends. Although Benjamin is shy and inexperienced, they have an affair. But then, when Benjamin falls in love with Mrs. Robinson's daughter, Elaine (Katharine Ross), a jealous and angry Mrs. Robinson does everything in her power to keep the young couple apart."
        },
        "defaultAudioLanguage": "en"
      },
      "contentDetails": {
        "duration": "PT1H45M58S",
        "dimension": "2d",
        "definition": "hd",
        "caption": "true",
        "licensedContent": true,
        "regionRestriction": {
          "allowed": [
            "US"
          ]
        },
        "contentRating": {},
        "projection": "rectangular"
      },
      "status": {
        "uploadStatus": "processed",
        "privacyStatus": "public",
        "license": "youtube",
        "embeddable": false,
        "publicStatsViewable": false,
        "madeForKids": false
      },
      "statistics": {
        "likeCount": "1512",
        "favoriteCount": "0",
        "commentCount": "0"
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"480\" height=\"270\" src=\"//www.youtube.com/embed/g1eZjGhN8oo\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      },
      "topicDetails": {
        "topicCategories": [
          "https://en.wikipedia.org/wiki/Entertainment",
          "https://en.wikipedia.org/wiki/Film"
        ]
      },
      "recordingDetails": {},
      "localizations": {
        "und": {
          "title": "The Graduate",
          "description": "Nominated for 7 Academy Awards and Winner for Best Directing, this groundbreaking film classic launched the career of two-time Oscar Winner Dustin Hoffman. During a party given by his parents to celebrate his graduation, Benjamin Braddock (Hoffman) is seduced by the sexy Mrs. Robinson (Anne Bancroft), the wife of his father's business partner and closes friends. Although Benjamin is shy and inexperienced, they have an affair. But then, when Benjamin falls in love with Mrs. Robinson's daughter, Elaine (Katharine Ross), a jealous and angry Mrs. Robinson does everything in her power to keep the young couple apart."
        }
      },
      "paidProductPlacementDetails": {
        "hasPaidProductPlacement": false
      }
    }
  ],
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 1
  }
}
