=== ryn-cx/not-yt-dlapi/src/not_yt_dlapi/video/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "items": {"type": "array", "items": {"type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "id": {"type": "string"}, "snippet": {"type": "object", "properties": {"publishedAt": {"format": "date-time", "type": "string"}, "channelId": {"type": "string"}, "title": {"type": "string"}, "description": {"type": "string"}, "thumbnails": {"type": "object", "properties": {"default": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "medium": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "high": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "standard": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "maxres": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "required": ["default", "high", "medium"]}, "channelTitle": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}, "categoryId": {"type": "string"}, "liveBroadcastContent": {"type": "string"}, "defaultLanguage": {"type": "string"}, "localized": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "defaultAudioLanguage": {"type": "string"}}, "required": ["categoryId", "channelId", "channelTitle", "defaultLanguage", "description", "liveBroadcastContent", "localized", "publishedAt", "tags", "thumbnails", "title"]}, "contentDetails": {"type": "object", "properties": {"duration": {"format": "duration", "type": "string"}, "dimension": {"anyOf": [{"type": "string"}, {"format": "duration", "type": "string"}]}, "definition": {"type": "string"}, "caption": {"type": "string"}, "licensedContent": {"type": "boolean"}, "contentRating": {"type": "object", "properties": {"ytRating": {"type": "string"}}}, "projection": {"type": "string"}, "regionRestriction": {"type": "object", "properties": {"allowed": {"type": "array", "items": {"type": "string"}}}, "required": ["allowed"]}}, "required": ["caption", "contentRating", "definition", "dimension", "duration", "licensedContent", "projection"]}, "status": {"type": "object", "properties": {"uploadStatus": {"type": "string"}, "privacyStatus": {"type": "string"}, "license": {"type": "string"}, "embeddable": {"type": "boolean"}, "publicStatsViewable": {"type": "boolean"}, "madeForKids": {"type": "boolean"}}, "required": ["embeddable", "license", "madeForKids", "privacyStatus", "publicStatsViewable", "uploadStatus"]}, "statistics": {"type": "object", "properties": {"viewCount": {"type": "string"}, "likeCount": {"type": "string"}, "favoriteCount": {"type": "string"}, "commentCount": {"type": "string"}}, "required": ["commentCount", "favoriteCount", "likeCount", "viewCount"]}, "player": {"type": "object", "properties": {"embedHtml": {"type": "string"}}, "required": ["embedHtml"]}, "recordingDetails": {"type": "object", "properties": {"locationDescription": {"type": "string"}, "location": {"type": "object", "properties": {"latitude": {"type": "number"}, "longitude": {"type": "number"}, "altitude": {"type": "integer"}}, "required": ["altitude", "latitude", "longitude"]}, "recordingDate": {"format": "date-time", "type": "string"}}}, "localizations": {"type": "object", "properties": {"de": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "en": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ru": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "ja": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}}, "required": ["en"]}, "paidProductPlacementDetails": {"type": "object", "properties": {"hasPaidProductPlacement": {"type": "boolean"}}, "required": ["hasPaidProductPlacement"]}, "topicDetails": {"type": "object", "properties": {"topicCategories": {"type": "array", "items": {"type": "string"}}}, "required": ["topicCategories"]}, "liveStreamingDetails": {"type": "object", "properties": {"activeLiveChatId": {"type": "string"}, "actualStartTime": {"type": "string", "format": "date-time"}, "actualEndTime": {"type": "string", "format": "date-time"}, "scheduledStartTime": {"type": "string", "format": "date-time"}}}}, "required": ["contentDetails", "etag", "id", "kind", "localizations", "paidProductPlacementDetails", "player", "recordingDetails", "snippet", "statistics", "status"]}}, "pageInfo": {"type": "object", "properties": {"totalResults": {"type": "integer"}, "resultsPerPage": {"type": "integer"}}, "required": ["resultsPerPage", "totalResults"]}}, "required": ["etag", "items", "kind", "pageInfo"]}

=== ryn-cx/not-yt-dlapi/tests/_files/Videos/TestList/TestVideo/jNQXAC9IVRw.json
{
  "kind": "youtube#videoListResponse",
  "etag": "7DKekg8h9s2DSsll0ZI4kn9bDUo",
  "items": [
    {
      "kind": "youtube#video",
      "etag": "MYjvrw3tObX23cGOungmQBPGQmw",
      "id": "jNQXAC9IVRw",
      "snippet": {
        "publishedAt": "2005-04-24T03:31:52Z",
        "channelId": "UC4QobU6STFB0P71PMvOGN5A",
        "title": "Me at the zoo",
        "description": "Microplastics are accumulating in human brains at an alarming rate\nhttps://www.youtube.com/watch?v=0PT5c1z3LL8\n\n\u201cNanoplastics and Human Health\u201d with Matthew J Campen, PhD, MSPH\nhttps://www.youtube.com/watch?v=RRBN_4L09Mg\n\n00:00 Intro\n00:05 The cool thing\n00:17 End",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg",
            "width": 480,
            "height": 360
          }
        },
        "channelTitle": "jawed",
        "tags": [
          "me at the zoo",
          "jawed karim",
          "first youtube video"
        ],
        "categoryId": "1",
        "liveBroadcastContent": "none",
        "defaultLanguage": "en",
        "localized": {
          "title": "Me at the zoo",
          "description": "Microplastics are accumulating in human brains at an alarming rate\nhttps://www.youtube.com/watch?v=0PT5c1z3LL8\n\n\u201cNanoplastics and Human Health\u201d with Matthew J Campen, PhD, MSPH\nhttps://www.youtube.com/watch?v=RRBN_4L09Mg\n\n00:00 Intro\n00:05 The cool thing\n00:17 End"
        },
        "defaultAudioLanguage": "en"
      },
      "contentDetails": {
        "duration": "PT19S",
        "dimension": "2d",
        "definition": "hd",
        "caption": "true",
        "licensedContent": true,
        "contentRating": {},
        "projection": "rectangular"
      },
      "status": {
        "uploadStatus": "processed",
        "privacyStatus": "public",
        "license": "youtube",
        "embeddable": true,
        "publicStatsViewable": false,
        "madeForKids": false
      },
      "statistics": {
        "viewCount": "405489293",
        "likeCount": "19385941",
        "favoriteCount": "0",
        "commentCount": "10564687"
      },
      "player": {
        "embedHtml": "<iframe width=\"480\" height=\"360\" src=\"//www.youtube.com/embed/jNQXAC9IVRw\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>"
      },
      "recordingDetails": {
        "locationDescription": "San Diego Zoo",
        "location": {
          "latitude": 32.7360353,
          "longitude": -117.1509849,
          "altitude": 0
        },
        "recordingDate": "2005-04-23T00:00:00Z"
      },
      "localizations": {
        "de": {
          "title": "Ich im Zoo",
          "description": "Das erste YouTube video. Vielleicht ist es Zeit zum Zoo zur\u00fcckzukehren?\n\n00:00 Intro\n00:05 Das coole Ding\n00:17 Ende"
        },
        "en": {
          "title": "Me at the zoo",
          "description": "Microplastics are accumulating in human brains at an alarming rate\nhttps://www.youtube.com/watch?v=0PT5c1z3LL8\n\n\u201cNanoplastics and Human Health\u201d with Matthew J Campen, PhD, MSPH\nhttps://www.youtube.com/watch?v=RRBN_4L09Mg\n\n00:00 Intro\n00:05 The cool thing\n00:17 End"
        }
      },
      "paidProductPlacementDetails": {
        "hasPaidProductPlacement": false
      }
    }
  ],
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 1
  }
}

=== ryn-cx/not-yt-dlapi/tests/_files/VideosModel/jNQXAC9IVRw.json
{
  "kind": "youtube#videoListResponse",
  "etag": "M5T8M5eOSZq1F41ER4eBc9Xj90o",
  "items": [
    {
      "kind": "youtube#video",
      "etag": "AK5RyLQSzProTficjrSm16L0PaU",
      "id": "jNQXAC9IVRw",
      "snippet": {
        "publishedAt": "2005-04-24T03:31:52Z",
        "channelId": "UC4QobU6STFB0P71PMvOGN5A",
        "title": "Me at the zoo",
        "description": "Microplastics are accumulating in human brains at an alarming rate\nhttps://www.youtube.com/watch?v=0PT5c1z3LL8\n\n“Nanoplastics and Human Health” with Matthew J Campen, PhD, MSPH\nhttps://www.youtube.com/watch?v=RRBN_4L09Mg\n\n00:00 Intro\n00:05 The cool thing\n00:17 End",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg",
            "width": 480,
            "height": 360
          }
        },
        "channelTitle": "jawed",
        "tags": [
          "me at the zoo",
          "jawed karim",
          "first youtube video"
        ],
        "categoryId": "1",
        "liveBroadcastContent": "none",
        "defaultLanguage": "en",
        "localized": {
          "title": "Me at the zoo",
          "description": "Microplastics are accumulating in human brains at an alarming rate\nhttps://www.youtube.com/watch?v=0PT5c1z3LL8\n\n“Nanoplastics and Human Health” with Matthew J Campen, PhD, MSPH\nhttps://www.youtube.com/watch?v=RRBN_4L09Mg\n\n00:00 Intro\n00:05 The cool thing\n00:17 End"
        },
        "defaultAudioLanguage": "en"
      },
      "contentDetails": {
        "duration": "PT19S",
        "dimension": "2d",
        "definition": "hd",
        "caption": "true",
        "licensedContent": true,
        "contentRating": {},
        "projection": "rectangular"
      },
      "status": {
        "uploadStatus": "processed",
        "privacyStatus": "public",
        "license": "youtube",
        "embeddable": true,
        "publicStatsViewable": false,
        "madeForKids": false
      },
      "statistics": {
        "viewCount": "405867021",
        "likeCount": "19398480",
        "favoriteCount": "0",
        "commentCount": "10566535"
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"480\" height=\"360\" src=\"//www.youtube.com/embed/jNQXAC9IVRw\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      },
      "recordingDetails": {
        "locationDescription": "San Diego Zoo",
        "location": {
          "latitude": 32.7360353,
          "longitude": -117.1509849,
          "altitude": 0
        },
        "recordingDate": "2005-04-23T00:00:00Z"
      },
      "localizations": {
        "en": {
          "title": "Me at the zoo",
          "description": "Microplastics are accumulating in human brains at an alarming rate\nhttps://www.youtube.com/watch?v=0PT5c1z3LL8\n\n“Nanoplastics and Human Health” with Matthew J Campen, PhD, MSPH\nhttps://www.youtube.com/watch?v=RRBN_4L09Mg\n\n00:00 Intro\n00:05 The cool thing\n00:17 End"
        },
        "de": {
          "title": "Ich im Zoo",
          "description": "Das erste YouTube video. Vielleicht ist es Zeit zum Zoo zurückzukehren?\n\n00:00 Intro\n00:05 Das coole Ding\n00:17 Ende"
        }
      },
      "paidProductPlacementDetails": {
        "hasPaidProductPlacement": false
      }
    }
  ],
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 1
  }
}
