=== ryn-cx/not-yt-dlapi/src/not_yt_dlapi/playlists/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "pageInfo": {"type": "object", "properties": {"totalResults": {"type": "integer"}, "resultsPerPage": {"type": "integer"}}, "required": ["resultsPerPage", "totalResults"]}, "items": {"type": "array", "items": {"type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "id": {"type": "string"}, "snippet": {"type": "object", "properties": {"publishedAt": {"type": "string", "format": "date-time"}, "channelId": {"type": "string"}, "title": {"type": "string"}, "description": {"type": "string"}, "thumbnails": {"type": "object", "properties": {"medium": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "standard": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "maxres": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "default": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "high": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "fhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "uhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "qhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "required": ["medium"]}, "channelTitle": {"type": "string"}, "localized": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "defaultLanguage": {"type": "string"}}, "required": ["channelId", "channelTitle", "description", "localized", "publishedAt", "thumbnails", "title"]}, "status": {"type": "object", "properties": {"privacyStatus": {"type": "string"}}, "required": ["privacyStatus"]}, "contentDetails": {"type": "object", "properties": {"itemCount": {"type": "integer"}}, "required": ["itemCount"]}, "player": {"type": "object", "properties": {"embedHtml": {"type": "string"}}, "required": ["embedHtml"]}, "localizations": {"type": "object", "properties": {"en": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ja": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "zh-TW": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sw": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "am": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "zh-CN": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "pl": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "kn": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ko": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "gu": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ru": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ca": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "km": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fa": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "az": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "de": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "hu": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "mr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "uk": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "cs": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "si": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "it": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ka": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sl": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fil": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ar": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "es-419": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "my": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sv": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "no": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "es-US": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "kk": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "hi": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "mk": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ne": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sq": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "bs": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "pt-PT": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sk": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "lt": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "as": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "te": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fr-CA": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "nl": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "or": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "mn": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "zh-HK": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "id": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "en-GB": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "el": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "en-IN": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "es": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ur": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "th": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "vi": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "bg": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "tr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "lv": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "is": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "et": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ta": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ms": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "da": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "hr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "pa": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "af": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sr-Latn": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "zu": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ky": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "hy": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "iw": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "pt": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "eu": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "bn": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fi": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ml": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ro": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "gl": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "be": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "lo": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "uz": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ar-XB": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "en-XA": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}}}}, "required": ["contentDetails", "etag", "id", "kind", "player", "snippet", "status"]}}, "nextPageToken": {"type": "string"}}, "required": ["etag", "items", "kind", "pageInfo"]}

=== ryn-cx/not-yt-dlapi/tests/_new_files/Playlists/TestList/TestMusicPlaylist/OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "T7ratB2TQVsrHFW6jemu4g2NZlE",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "eOi8hb2_LkrqCTOaMksvGmVS3IM",
      "id": "OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc",
      "snippet": {
        "publishedAt": "2019-01-30T11:15:19.1882Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "VIDA",
        "description": "",
        "thumbnails": {
          "medium": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc/mqdefault.jpg?sqp=CPCWm9QGir7X7AMICKbyqb0GEAE=&rs=AOn4CLCLoSotvbwIZ1NT85k_T_9Zv9IXFg&v=1739225382",
            "width": 180,
            "height": 180
          },
          "standard": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc/sddefault.jpg?sqp=CPCWm9QGir7X7AMICKbyqb0GEAE=&rs=AOn4CLCfd_JDezfdxqHhYhlzDyuKf-AOYA&v=1739225382",
            "width": 640,
            "height": 640
          },
          "maxres": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc/maxresdefault.jpg?sqp=CPCWm9QGir7X7AMICKbyqb0GEAE=&rs=AOn4CLDUJYF7W6XZNsF9P_rLT3t8NXE-YQ&v=1739225382",
            "width": 1200,
            "height": 1200
          }
        },
        "channelTitle": "YouTube",
        "localized": {
          "title": "VIDA",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 15
      },
      "player": {
        "embedHtml": "<iframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>"
      }
    }
  ]
}

=== ryn-cx/not-yt-dlapi/tests/_files/PlaylistsModel/OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "5A5K9vE3DJ_TOEwBtkLMCvU9bY8",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "-gIAXFuDxIET9yG_MkwhwKNJklA",
      "id": "OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8",
      "snippet": {
        "publishedAt": "2025-08-10T03:29:50.157985Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "God Does Like Ugly (Preluxe Edition)",
        "description": "",
        "thumbnails": {
          "medium": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8/mqdefault.jpg?sqp=CIyFqdQGir7X7AMICLCk4MQGEAE=&rs=AOn4CLA0wCwKUTFxiTL9k2GVlzMB8TI7mQ&v=1754796592",
            "width": 180,
            "height": 180
          },
          "standard": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8/sddefault.jpg?sqp=CIyFqdQGir7X7AMICLCk4MQGEAE=&rs=AOn4CLDSKns2vPTGTxA3mQp5oqR97CccyA&v=1754796592",
            "width": 640,
            "height": 640
          },
          "maxres": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8/maxresdefault.jpg?sqp=CIyFqdQGir7X7AMICLCk4MQGEAE=&rs=AOn4CLCPiiDbV__liOCpqWZ9DfuVIQcR2g&v=1754796592",
            "width": 1200,
            "height": 1200
          }
        },
        "channelTitle": "YouTube",
        "localized": {
          "title": "God Does Like Ugly (Preluxe Edition)",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 19
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      }
    }
  ]
}

=== ryn-cx/not-yt-dlapi/tests/_files/Playlists/TestPlaylists/OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "GOQ0yqTbyEl8n69s0urOso3SfgM",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "1GKjgK04bxi9C9cCRExHV-odCZM",
      "id": "OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8",
      "snippet": {
        "publishedAt": "2025-08-10T03:29:50.157985Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "God Does Like Ugly (Preluxe Edition)",
        "description": "",
        "thumbnails": {
          "medium": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8/mqdefault.jpg?sqp=CKCOodQGir7X7AMICLCk4MQGEAE=&rs=AOn4CLDZOk39QaEOGLiPc1T-l3iXyKH6OQ&v=1754796592",
            "width": 180,
            "height": 180
          },
          "standard": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8/sddefault.jpg?sqp=CKCOodQGir7X7AMICLCk4MQGEAE=&rs=AOn4CLArbAcvchh429zs8JA3L5qyVdHyhw&v=1754796592",
            "width": 640,
            "height": 640
          },
          "maxres": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8/maxresdefault.jpg?sqp=CKCOodQGir7X7AMICLCk4MQGEAE=&rs=AOn4CLBWbKpe1e2Jky8-BhNoe7ck_eIsiw&v=1754796592",
            "width": 1200,
            "height": 1200
          }
        },
        "channelTitle": "YouTube",
        "localized": {
          "title": "God Does Like Ugly (Preluxe Edition)",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 19
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=OLAK5uy_mKcftf5tOvVhq-CsutohYLKrB1l8PqCG8\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      }
    }
  ]
}

=== ryn-cx/not-yt-dlapi/tests/_files/Playlists/TestPlaylists/PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "rR0NQOiPN0HEhbdD6lYp454p0c4",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "LHyGacy_UOCS4V5p650Kkv5RELw",
      "id": "PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
      "snippet": {
        "publishedAt": "2020-04-28T07:33:06.091651Z",
        "channelId": "UC4QobU6STFB0P71PMvOGN5A",
        "title": "YouTube",
        "description": "",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg",
            "width": 480,
            "height": 360
          },
          "standard": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/sddefault.jpg",
            "width": 640,
            "height": 480
          },
          "maxres": {
            "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/maxresdefault.jpg",
            "width": 1280,
            "height": 720
          }
        },
        "channelTitle": "jawed",
        "localized": {
          "title": "YouTube",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 4
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      }
    }
  ]
}

=== ryn-cx/not-yt-dlapi/scratch/playlist.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "06QXfUhNpbV33lCVFb3pSdfwGPQ",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "zhNrfebyLrF9wT7nRBxOW5YK4NA",
      "id": "OLAK5uy_lVxq_QCXDlleCnpsszQyiFextilkX12_w",
      "snippet": {
        "publishedAt": "2024-03-21T17:41:07.624267Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "WE DON'T TRUST YOU",
        "description": "",
        "thumbnails": {
          "medium": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_lVxq_QCXDlleCnpsszQyiFextilkX12_w/mqdefault.jpg?sqp=CPyrm9QGir7X7AMICPaUrb0GEAE=&rs=AOn4CLBlL7ozsib79RvpT7w-_CiTpXrJuA&v=1739278966",
            "width": 180,
            "height": 180
          },
          "standard": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_lVxq_QCXDlleCnpsszQyiFextilkX12_w/sddefault.jpg?sqp=CPyrm9QGir7X7AMICPaUrb0GEAE=&rs=AOn4CLBtAtbAkH_suf68D9En0t60g3P-FA&v=1739278966",
            "width": 640,
            "height": 640
          },
          "maxres": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_lVxq_QCXDlleCnpsszQyiFextilkX12_w/maxresdefault.jpg?sqp=CPyrm9QGir7X7AMICPaUrb0GEAE=&rs=AOn4CLCIh12rmpeKbbLkT12kYdV3u19eeQ&v=1739278966",
            "width": 1200,
            "height": 1200
          }
        },
        "channelTitle": "YouTube",
        "localized": {
          "title": "WE DON'T TRUST YOU",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 17
      },
      "player": {
        "embedHtml": "<iframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=OLAK5uy_lVxq_QCXDlleCnpsszQyiFextilkX12_w\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>"
      }
    }
  ]
}

=== ryn-cx/not-yt-dlapi/tests/_files/Playlists/TestList/TestMusicPlaylist/OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "4PKn33tvz1d3FsDd6Ia7SmYEBw8",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "anBvHk55rMxNvXZ-Gp1Xtplisbc",
      "id": "OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc",
      "snippet": {
        "publishedAt": "2019-01-30T11:15:19.1882Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "VIDA",
        "description": "",
        "thumbnails": {
          "medium": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc/mqdefault.jpg?sqp=CNySmdQGir7X7AMICKbyqb0GEAE=&rs=AOn4CLAXrZmCaZMtpt2fhjfWE5iOUKcgcg&v=1739225382",
            "width": 180,
            "height": 180
          },
          "standard": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc/sddefault.jpg?sqp=CNySmdQGir7X7AMICKbyqb0GEAE=&rs=AOn4CLBpEeve1cvb6TUW0RcQU8EgDdyMBw&v=1739225382",
            "width": 640,
            "height": 640
          },
          "maxres": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc/maxresdefault.jpg?sqp=CNySmdQGir7X7AMICKbyqb0GEAE=&rs=AOn4CLDMYP2wTMEikPb1q8F7B6pk9gAvzw&v=1739225382",
            "width": 1200,
            "height": 1200
          }
        },
        "channelTitle": "YouTube",
        "localized": {
          "title": "VIDA",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 15
      },
      "player": {
        "embedHtml": "<iframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=OLAK5uy_kgvDzTzHW2NHKXbZ6kzcoCY-XfVE0c-Sc\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>"
      }
    }
  ]
}
