=== ryn-cx/not-yt-dlapi/src/not_yt_dlapi/playlists/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "pageInfo": {"type": "object", "properties": {"totalResults": {"type": "integer"}, "resultsPerPage": {"type": "integer"}}, "required": ["resultsPerPage", "totalResults"]}, "items": {"type": "array", "items": {"type": "object", "properties": {"kind": {"type": "string"}, "etag": {"type": "string"}, "id": {"type": "string"}, "snippet": {"type": "object", "properties": {"publishedAt": {"type": "string", "format": "date-time"}, "channelId": {"type": "string"}, "title": {"type": "string"}, "description": {"type": "string"}, "thumbnails": {"type": "object", "properties": {"medium": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "standard": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "maxres": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "default": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "high": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "fhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "uhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}, "qhd": {"type": "object", "properties": {"url": {"type": "string"}, "width": {"type": "integer"}, "height": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "required": ["medium"]}, "channelTitle": {"type": "string"}, "localized": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["description", "title"]}, "defaultLanguage": {"type": "string"}}, "required": ["channelId", "channelTitle", "description", "localized", "publishedAt", "thumbnails", "title"]}, "status": {"type": "object", "properties": {"privacyStatus": {"type": "string"}}, "required": ["privacyStatus"]}, "contentDetails": {"type": "object", "properties": {"itemCount": {"type": "integer"}}, "required": ["itemCount"]}, "player": {"type": "object", "properties": {"embedHtml": {"type": "string"}}, "required": ["embedHtml"]}, "localizations": {"type": "object", "properties": {"en": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "ja": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}}, "required": ["title"]}, "zh-TW": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sw": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "am": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "zh-CN": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "pl": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "kn": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ko": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "gu": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ru": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ca": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "km": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fa": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "az": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "de": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "hu": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "mr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "uk": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "cs": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "si": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "it": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ka": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sl": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fil": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ar": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "es-419": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "my": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sv": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "no": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "es-US": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "kk": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "hi": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "mk": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ne": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sq": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "bs": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "pt-PT": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sk": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "lt": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "as": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "te": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fr-CA": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "nl": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "or": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "mn": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "zh-HK": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "id": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "en-GB": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "el": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "en-IN": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "es": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ur": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "th": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "vi": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "bg": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "tr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "lv": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "is": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "et": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ta": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ms": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "da": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "hr": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "pa": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "af": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "sr-Latn": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "zu": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ky": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "hy": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "iw": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "pt": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "eu": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "bn": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "fi": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ml": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ro": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "gl": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "be": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "lo": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "uz": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "ar-XB": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}, "en-XA": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}}}}, "required": ["contentDetails", "etag", "id", "kind", "player", "snippet", "status"]}}, "nextPageToken": {"type": "string"}}, "required": ["etag", "items", "kind", "pageInfo"]}

=== ryn-cx/not-yt-dlapi/tests/_files/Playlists/TestPlaylists/UU4QobU6STFB0P71PMvOGN5A.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "_L-PhdYXYomObWJPa9pqN3fXBLM",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "-Hgv1GxRbEA4UONl2_2d7J3aHB0",
      "id": "UU4QobU6STFB0P71PMvOGN5A",
      "snippet": {
        "publishedAt": "2020-02-20T08:00:00Z",
        "channelId": "UC4QobU6STFB0P71PMvOGN5A",
        "title": "Uploads from jawed",
        "description": "",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg",
            "width": 480,
            "height": 360
          }
        },
        "channelTitle": "jawed",
        "defaultLanguage": "en",
        "localized": {
          "title": "Uploads from jawed",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 1
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=UU4QobU6STFB0P71PMvOGN5A\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      },
      "localizations": {
        "ca": {
          "title": "Pujades de: jawed"
        },
        "lo": {
          "title": "ການອັບໂຫຼດຈາກ jawed"
        },
        "ar-XB": {
          "title": "\u200f\u202eUploads\u202c\u200f \u200f\u202efrom\u202c\u200f jawed"
        },
        "pt-PT": {
          "title": "Carregamentos de jawed"
        },
        "as": {
          "title": "jawedৰ পৰা আপল’ডসমূহ"
        },
        "ro": {
          "title": "Încărcări de la jawed"
        },
        "iw": {
          "title": "העלאות מ-jawed"
        },
        "fr-CA": {
          "title": "Vidéos mises en ligne par jawed"
        },
        "de": {
          "title": "Uploads von jawed"
        },
        "pt": {
          "title": "Uploads de jawed"
        },
        "sv": {
          "title": "Uppladdat från jawed"
        },
        "en": {
          "title": "Uploads from jawed",
          "description": ""
        },
        "zh-HK": {
          "title": "由「jawed」上載"
        },
        "bn": {
          "title": "jawed-এর আপলোড করা ভিডিও"
        },
        "am": {
          "title": "ሰቀላዎች ከjawed"
        },
        "fa": {
          "title": "بارگذاری\u200cهای jawed"
        },
        "ms": {
          "title": "Muat naik daripada jawed"
        },
        "ml": {
          "title": "jawed-ലെ അപ്\u200cലോഡുകൾ"
        },
        "is": {
          "title": "Upphleðslur frá jawed"
        },
        "ur": {
          "title": "jawed کی جانب سے اپ لوڈز"
        },
        "ar": {
          "title": "فيديوهات محمّلة من قناة jawed"
        },
        "or": {
          "title": "jawedରୁ ଅପ୍\u200d\u200dଲୋଡ୍\u200cଗୁଡ଼ିକ"
        },
        "sq": {
          "title": "Ngarkime nga jawed"
        },
        "da": {
          "title": "Uploads fra jawed"
        },
        "fr": {
          "title": "Vidéos mises en ligne par jawed"
        },
        "mr": {
          "title": "jawed वरील अपलोड"
        },
        "ka": {
          "title": "ატვირთვები jawed-დან"
        },
        "lt": {
          "title": "Turinys, kurį įkėlė jawed"
        },
        "vi": {
          "title": "Video tải lên từ jawed"
        },
        "ja": {
          "title": "jawed さんのアップロード動画"
        },
        "es-419": {
          "title": "Cargas de jawed"
        },
        "id": {
          "title": "Upload dari jawed"
        },
        "uz": {
          "title": "jawed kanaliga yuklanganlar"
        },
        "sl": {
          "title": "Naloženi videoposnetki iz kanala jawed"
        },
        "si": {
          "title": "jawed වෙතින් උඩුගත කිරීම්"
        },
        "ne": {
          "title": "jawed ले अपलोड गरेका"
        },
        "es": {
          "title": "Vídeos subidos de jawed"
        },
        "no": {
          "title": "Opplastinger fra jawed"
        },
        "cs": {
          "title": "Nahráno z kanálu jawed"
        },
        "en-IN": {
          "title": "Uploads from jawed"
        },
        "lv": {
          "title": "Kanāla jawed augšupielādes"
        },
        "ko": {
          "title": "jawed에서 업로드한 동영상"
        },
        "nl": {
          "title": "Uploads van jawed"
        },
        "be": {
          "title": "Запампоўкі з канала \"jawed\""
        },
        "my": {
          "title": "jawed မှ အပ်လုဒ်များ"
        },
        "fil": {
          "title": "Mga upload mula sa jawed"
        },
        "az": {
          "title": "jawed kanalından yükləmələr"
        },
        "th": {
          "title": "อัปโหลดจาก jawed"
        },
        "en-XA": {
          "title": "[Ûþļöåðš ƒŕöm ᐅjawedᐊ one two three four]"
        },
        "tr": {
          "title": "jawed kanalının yüklemeleri"
        },
        "zu": {
          "title": "Okulayishiwe okuvela ku-jawed"
        },
        "sr-Latn": {
          "title": "Videi otpremljeni sa jawed"
        },
        "el": {
          "title": "Μεταφορτώσεις από jawed"
        },
        "et": {
          "title": "Üleslaadimised kanalilt jawed"
        },
        "kk": {
          "title": "jawed арнасынан жүктеп салынған бейнелер"
        },
        "ru": {
          "title": "Видео с канала \"jawed\""
        },
        "bg": {
          "title": "Качвания от jawed"
        },
        "gu": {
          "title": "jawedમાંથી અપલોડ"
        },
        "hu": {
          "title": "Feltöltések innen: jawed"
        },
        "ky": {
          "title": "jawed каналынан жүктөлүп берилгендер"
        },
        "hr": {
          "title": "Prijenosi kanala jawed"
        },
        "gl": {
          "title": "Cargas de jawed"
        },
        "pl": {
          "title": "Przesłane przez kanał jawed"
        },
        "fi": {
          "title": "Videoita kanavalta jawed"
        },
        "bs": {
          "title": "Otpremanja s kanala jawed"
        },
        "mn": {
          "title": "jawed-с байршуулсан"
        },
        "uk": {
          "title": "Завантаження з каналу \"jawed\""
        },
        "sw": {
          "title": "Video zilizopakiwa kutoka jawed"
        },
        "it": {
          "title": "Video caricati da jawed"
        },
        "eu": {
          "title": "\"jawed\" kanalak kargatutakoak"
        },
        "te": {
          "title": "jawed నుండి అప్\u200cలోడ్\u200cలు"
        },
        "af": {
          "title": "Oplaaie vanaf jawed"
        },
        "zh-CN": {
          "title": "来自“jawed”上传的内容"
        },
        "hi": {
          "title": "jawed के अपलोड किए गए वीडियो"
        },
        "ta": {
          "title": "jawed சேனல் பதிவேற்றியவை"
        },
        "en-GB": {
          "title": "Uploads from jawed"
        },
        "sr": {
          "title": "Видеи отпремљени са jawed"
        },
        "pa": {
          "title": "jawed ਦੇ ਅੱਪਲੋਡ"
        },
        "km": {
          "title": "ការង្ហោះ\u200bពី jawed"
        },
        "zh-TW": {
          "title": "「jawed」上傳的影片"
        },
        "es-US": {
          "title": "Cargas de jawed"
        },
        "hy": {
          "title": "Վերբեռնումներ jawed-ից"
        },
        "mk": {
          "title": "Прикачувања од jawed"
        },
        "sk": {
          "title": "Nahrané videá z kanála jawed"
        },
        "kn": {
          "title": "jawed ನಿಂದ ಅಪ್\u200cಲೋಡ್\u200cಗಳು"
        }
      }
    }
  ]
}

=== ryn-cx/not-yt-dlapi/tests/_files/PlaylistsModel/UU4QobU6STFB0P71PMvOGN5A.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "JogNZivVjbQ8hIDUpoKVe-65Y7Y",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "J03vhmHK5LMCTuELxY9Ty98scpg",
      "id": "UU4QobU6STFB0P71PMvOGN5A",
      "snippet": {
        "publishedAt": "2020-02-20T08:00:00Z",
        "channelId": "UC4QobU6STFB0P71PMvOGN5A",
        "title": "Uploads from jawed",
        "description": "",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg",
            "width": 480,
            "height": 360
          }
        },
        "channelTitle": "jawed",
        "defaultLanguage": "en",
        "localized": {
          "title": "Uploads from jawed",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 1
      },
      "player": {
        "embedHtml": "\u003ciframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=UU4QobU6STFB0P71PMvOGN5A\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen\u003e\u003c/iframe\u003e"
      },
      "localizations": {
        "ne": {
          "title": "jawed ले अपलोड गरेका"
        },
        "bg": {
          "title": "Качвания от jawed"
        },
        "sr": {
          "title": "Видеи отпремљени са jawed"
        },
        "az": {
          "title": "jawed kanalından yükləmələr"
        },
        "pa": {
          "title": "jawed ਦੇ ਅੱਪਲੋਡ"
        },
        "en": {
          "title": "Uploads from jawed",
          "description": ""
        },
        "sr-Latn": {
          "title": "Videi otpremljeni sa jawed"
        },
        "ka": {
          "title": "ატვირთვები jawed-დან"
        },
        "te": {
          "title": "jawed నుండి అప్\u200cలోడ్\u200cలు"
        },
        "pl": {
          "title": "Przesłane przez kanał jawed"
        },
        "sq": {
          "title": "Ngarkime nga jawed"
        },
        "el": {
          "title": "Μεταφορτώσεις από jawed"
        },
        "hy": {
          "title": "Վերբեռնումներ jawed-ից"
        },
        "th": {
          "title": "อัปโหลดจาก jawed"
        },
        "eu": {
          "title": "\"jawed\" kanalak kargatutakoak"
        },
        "zh-HK": {
          "title": "由「jawed」上載"
        },
        "da": {
          "title": "Uploads fra jawed"
        },
        "si": {
          "title": "jawed වෙතින් උඩුගත කිරීම්"
        },
        "es": {
          "title": "Vídeos subidos de jawed"
        },
        "hi": {
          "title": "jawed के अपलोड किए गए वीडियो"
        },
        "zh-TW": {
          "title": "「jawed」上傳的影片"
        },
        "lt": {
          "title": "Turinys, kurį įkėlė jawed"
        },
        "lo": {
          "title": "ການອັບໂຫຼດຈາກ jawed"
        },
        "bn": {
          "title": "jawed-এর আপলোড করা ভিডিও"
        },
        "fr-CA": {
          "title": "Vidéos mises en ligne par jawed"
        },
        "iw": {
          "title": "העלאות מ-jawed"
        },
        "ja": {
          "title": "jawed さんのアップロード動画"
        },
        "gu": {
          "title": "jawedમાંથી અપલોડ"
        },
        "ms": {
          "title": "Muat naik daripada jawed"
        },
        "sl": {
          "title": "Naloženi videoposnetki iz kanala jawed"
        },
        "mk": {
          "title": "Прикачувања од jawed"
        },
        "be": {
          "title": "Запампоўкі з канала \"jawed\""
        },
        "uz": {
          "title": "jawed kanaliga yuklanganlar"
        },
        "bs": {
          "title": "Otpremanja s kanala jawed"
        },
        "en-IN": {
          "title": "Uploads from jawed"
        },
        "ur": {
          "title": "jawed کی جانب سے اپ لوڈز"
        },
        "ru": {
          "title": "Видео с канала \"jawed\""
        },
        "ky": {
          "title": "jawed каналынан жүктөлүп берилгендер"
        },
        "es-US": {
          "title": "Cargas de jawed"
        },
        "it": {
          "title": "Video caricati da jawed"
        },
        "mn": {
          "title": "jawed-с байршуулсан"
        },
        "zh-CN": {
          "title": "来自“jawed”上传的内容"
        },
        "nl": {
          "title": "Uploads van jawed"
        },
        "kk": {
          "title": "jawed арнасынан жүктеп салынған бейнелер"
        },
        "en-GB": {
          "title": "Uploads from jawed"
        },
        "lv": {
          "title": "Kanāla jawed augšupielādes"
        },
        "uk": {
          "title": "Завантаження з каналу \"jawed\""
        },
        "hu": {
          "title": "Feltöltések innen: jawed"
        },
        "hr": {
          "title": "Prijenosi kanala jawed"
        },
        "sk": {
          "title": "Nahrané videá z kanála jawed"
        },
        "de": {
          "title": "Uploads von jawed"
        },
        "en-XA": {
          "title": "[Ûþļöåðš ƒŕöm ᐅjawedᐊ one two three four]"
        },
        "tr": {
          "title": "jawed kanalının yüklemeleri"
        },
        "sv": {
          "title": "Uppladdat från jawed"
        },
        "fil": {
          "title": "Mga upload mula sa jawed"
        },
        "af": {
          "title": "Oplaaie vanaf jawed"
        },
        "mr": {
          "title": "jawed वरील अपलोड"
        },
        "no": {
          "title": "Opplastinger fra jawed"
        },
        "pt": {
          "title": "Uploads de jawed"
        },
        "fr": {
          "title": "Vidéos mises en ligne par jawed"
        },
        "pt-PT": {
          "title": "Carregamentos de jawed"
        },
        "zu": {
          "title": "Okulayishiwe okuvela ku-jawed"
        },
        "am": {
          "title": "ሰቀላዎች ከjawed"
        },
        "fi": {
          "title": "Videoita kanavalta jawed"
        },
        "fa": {
          "title": "بارگذاری\u200cهای jawed"
        },
        "ar": {
          "title": "فيديوهات محمّلة من قناة jawed"
        },
        "gl": {
          "title": "Cargas de jawed"
        },
        "ar-XB": {
          "title": "\u200f\u202eUploads\u202c\u200f \u200f\u202efrom\u202c\u200f jawed"
        },
        "as": {
          "title": "jawedৰ পৰা আপল’ডসমূহ"
        },
        "ta": {
          "title": "jawed சேனல் பதிவேற்றியவை"
        },
        "km": {
          "title": "ការង្ហោះ\u200bពី jawed"
        },
        "id": {
          "title": "Upload dari jawed"
        },
        "ko": {
          "title": "jawed에서 업로드한 동영상"
        },
        "my": {
          "title": "jawed မှ အပ်လုဒ်များ"
        },
        "or": {
          "title": "jawedରୁ ଅପ୍\u200d\u200dଲୋଡ୍\u200cଗୁଡ଼ିକ"
        },
        "ml": {
          "title": "jawed-ലെ അപ്\u200cലോഡുകൾ"
        },
        "et": {
          "title": "Üleslaadimised kanalilt jawed"
        },
        "sw": {
          "title": "Video zilizopakiwa kutoka jawed"
        },
        "kn": {
          "title": "jawed ನಿಂದ ಅಪ್\u200cಲೋಡ್\u200cಗಳು"
        },
        "ro": {
          "title": "Încărcări de la jawed"
        },
        "vi": {
          "title": "Video tải lên từ jawed"
        },
        "es-419": {
          "title": "Cargas de jawed"
        },
        "ca": {
          "title": "Pujades de: jawed"
        },
        "is": {
          "title": "Upphleðslur frá jawed"
        },
        "cs": {
          "title": "Nahráno z kanálu jawed"
        }
      }
    }
  ]
}

=== ryn-cx/not-yt-dlapi/tests/_files/GetPlaylists/TestMusicPlaylist/OLAK5uy_lfFeKLvDqhTQwmfolUjDBfbyrjjgdmYcE.json
{
  "kind": "youtube#playlistListResponse",
  "etag": "xi3DTlG4S_c1uHv9Z1fFZRzoqg8",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 50
  },
  "items": [
    {
      "kind": "youtube#playlist",
      "etag": "5Umkn82urCdNPdu_kaOSk12G_RU",
      "id": "OLAK5uy_lfFeKLvDqhTQwmfolUjDBfbyrjjgdmYcE",
      "snippet": {
        "publishedAt": "2025-07-10T14:48:06.348552Z",
        "channelId": "UCBR8-60-B28hp2BmDPdntcQ",
        "title": "Let God Sort Em Out",
        "description": "",
        "thumbnails": {
          "medium": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_lfFeKLvDqhTQwmfolUjDBfbyrjjgdmYcE/mqdefault.jpg?sqp=CMSHl9QGir7X7AMICKmlv8MGEAE=&rs=AOn4CLBzB8wShNsCvM-w_D7VjAZW3iHN3w&v=1752158889",
            "width": 180,
            "height": 180
          },
          "standard": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_lfFeKLvDqhTQwmfolUjDBfbyrjjgdmYcE/sddefault.jpg?sqp=CMSHl9QGir7X7AMICKmlv8MGEAE=&rs=AOn4CLBBjUYihbfgKnFAOxk9a03ydGAnMQ&v=1752158889",
            "width": 640,
            "height": 640
          },
          "maxres": {
            "url": "https://i9.ytimg.com/s_p/OLAK5uy_lfFeKLvDqhTQwmfolUjDBfbyrjjgdmYcE/maxresdefault.jpg?sqp=CMSHl9QGir7X7AMICKmlv8MGEAE=&rs=AOn4CLBA1sH1M1rlD7qsa8k6J0Ee8vV0bw&v=1752158889",
            "width": 1200,
            "height": 1200
          }
        },
        "channelTitle": "YouTube",
        "localized": {
          "title": "Let God Sort Em Out",
          "description": ""
        }
      },
      "status": {
        "privacyStatus": "public"
      },
      "contentDetails": {
        "itemCount": 13
      },
      "player": {
        "embedHtml": "<iframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=OLAK5uy_lfFeKLvDqhTQwmfolUjDBfbyrjjgdmYcE\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>"
      }
    }
  ]
}
